[server]
port = "8080"

[database]
host = "localhost"
port = "3306"
user = "XXX"
password = "XXX"
dbname = "hafez_poems"

[redis]
host = "localhost"
port = "6379"
password = ""
db = 0

[minio]
audioendpoint = "http://localhost:9000/hafez-media/mp3"
imageendpoint = "http://localhost:9000/hafez-media/images"